### ISSUE TITLE
liwan crashes on vserver

### ISSUE THREAD

**Issue by Samhamsam** [explodingcamera/liwan#21]
Hi, thank you for this awesome project. I wanted to run liwan on a vserver with 1cpu and 1gb ram. But did limit cpu to 0.5 and ram to 256mb. When i call a website where i put the <script> liwan crashes, even without the limits. Just to be clear, i only call it once. There is no other traffic. This is my compose:

```
services:
  liwan:
    image: ghcr.io/explodingcamera/liwan:1.1
    container_name: liwan
    ports:
        - "127.0.0.1:9042:9042"
    volumes:
        - liwan-data:/data
    # See https://liwan.dev/reference/configuration for all configuration options
    environment:
        - LIWAN_BASE_URL=https://my-website.com
        - LIWAN_DUCKDB_MEMORY_LIMIT=256m
        - LIWAN_DUCKDB_THREADS=1
        - LIWAN_DISABLE_FAVICONS=true
    networks:
      - web
    mem_limit: 300m
    cpus: 0.5

volumes:
  liwan-data:

networks:
  web:
    external: true
```
When i monitor with htop and docker stats i see that they go up to 100% and then crashes.

The admin interface works.

Is this an issue with the low resources or other problem?
